singleQuote: true
trailingComma: all
tabWidth: 2
endOfLine: lf
printWidth: 120
overrides:
  - files:
      - '*.js'
      - '*.ts'
      - '*.jsx'
      - '*.tsx'
      - '*.vue'
    options:
      tabWidth: 4
