singleQuote: true
trailingComma: all
tabWidth: 2
endOfLine: lf
printWidth: 120
overrides:
  - files:
      - '*.js'
      - '*.ts'
    options:
      tabWidth: 4
  - files: 'src/browser/**/*.html'
    options:
      parser: angular
