language: node_js
node_js: lts/*
branches:
  only:
  - master
script: npm run build
deploy:
  provider: pages
  on:
    branch: master
  skip_cleanup: true
  keep_history: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: ./dist