shellEmulator: true
dedupePeers: true

allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@scarf/scarf': false
  es5-ext: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false

publicHoistPattern:
  - fastify
