name: browser

on:
    pull_request:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - name: Install
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false
            - name: Set env
              run: node ./scripts/info.js

            - name: Build
              run: yarn build:browser
            - name: Upload artifact
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: browser
                  path: ./dist/browser
