name: build

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          pnpm-version: 8

  tool:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          pnpm-version: 8
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: pnpm build:tool
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tool
          path: ./dist/tool
      - name: Test
        run: pnpm test:tool

      - name: Prepare release
        if: github.ref == 'refs/heads/master'
        run: |
          cd ./dist/tool
          pnpm install --prod --prefer-offline
          zip -r ../../release.zip .
      - name: Publish release
        uses: ncipollo/release-action@v1.12.0
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.head_commit.message }}
          tag: v${{ env.PACKAGE_VERSION }}
          commit: ${{ github.sha }}
          artifacts: ./release.zip
          allowUpdates: true

  server:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          pnpm-version: 8
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: pnpm build:server
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: ./dist
      - name: Test
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          DB_PATH: db
          DB_REPO: EhTagTranslation/Database
        run: pnpm test:server
      - name: Install Prod
        if: github.ref == 'refs/heads/master'
        run: pnpm install --prod --prefer-offline
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

  browser:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          pnpm-version: 8
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: pnpm build:browser
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: browser
          path: ./dist/browser
      - name: Test
        run: pnpm test:browser
