name: build

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  tool:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '12'
      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: yarn build:tool
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tool
          path: ./dist
      - name: Test
        run: yarn test:tool

      - name: Prepare release
        if: github.ref == 'refs/heads/master'
        run: |
          node ./scripts/tool.js
          cd ./dist
          yarn install --prefer-offline
          zip -r ../release.zip .
      - name: Publish release
        uses: ncipollo/release-action@v1.8.6
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.head_commit.message }}
          tag: v${{ env.PACKAGE_VERSION}}
          commit: ${{ github.sha }}
          artifacts: ./release.zip
          allowUpdates: true

  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '12'
      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: yarn build:server
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: ./dist
      - name: Test
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          DB_PATH: db
          DB_REPO: EhTagTranslation/Database
        run: yarn test:server

  browser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '12'
      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: yarn build:browser
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: browser
          path: ./dist/browser
      - name: Test
        run: yarn test:browser
