name: build

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  tool:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: yarn build:tool
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tool
          path: ./dist/tool
      - name: Test
        run: yarn test:tool

      - name: Prepare release
        if: github.ref == 'refs/heads/master'
        run: |
          cd ./dist/tool
          yarn install --prefer-offline
          zip -r ../../release.zip .
      - name: Publish release
        uses: ncipollo/release-action@v1.11.2
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.head_commit.message }}
          tag: v${{ env.PACKAGE_VERSION }}
          commit: ${{ github.sha }}
          artifacts: ./release.zip
          allowUpdates: true

  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: yarn build:server
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: ./dist
      - name: Test
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          DB_PATH: db
          DB_REPO: EhTagTranslation/Database
        run: yarn test:server
      - name: Install Prod
        if: github.ref == 'refs/heads/master'
        uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only

  browser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16'
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Set env
        run: node ./scripts/info.js

      - name: Build
        run: yarn build:browser
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: browser
          path: ./dist/browser
      - name: Test
        run: yarn test:browser
