name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - name: Install
              uses: bahmutov/npm-install@v1

            - name: Build
              run: yarn build:server
            - name: Upload artifact
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: server
                  path: ./dist

            - name: Prepare deploy
              run: |
                  node ./scripts/server.js
                  cd ./dist
                  yarn install --prefer-offline
            - name: Deploy to Azure webapp
              uses: azure/webapps-deploy@v1
              if: github.ref == 'refs/heads/master'
              with:
                  app-name: ehtt
                  publish-profile: ${{ secrets.AzureWebAppPublishProfile }}
                  package: ./dist
