name: tool

on:
    pull_request:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - name: Install
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false
            - name: Set env
              run: node ./scripts/info.js

            - name: Build
              run: yarn build:tool
            - name: Upload artifact
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: tool
                  path: ./dist

            - name: Prepare release
              if: github.ref == 'refs/heads/master'
              run: |
                  node ./scripts/tool.js
                  cd ./dist
                  yarn install --prefer-offline
                  zip -r ../release.zip .
            - name: Publish release
              uses: ncipollo/release-action@v1
              if: github.ref == 'refs/heads/master'
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: ${{ github.event.head_commit.message }}
                  tag: v${{ env.PACKAGE_VERSION}}
                  commit: ${{ github.sha }}
                  artifacts: ./release.zip
                  allowUpdates: true
